import { Jaro } from "next/font/google"; // Use a supported font
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jaro = Jaro({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-jaro",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jaro.className}`}>
        {children}
      </body>
    </html>
  );
}
